// src/components/CreateTodoModal.jsx
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { createTodo } from '../api/todos';

const CreateTodoModal = ({ onClose }) => {
  const [title, setTitle] = useState('');
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: createTodo,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['todos'] });
      onClose();
    }
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    mutation.mutate({ title, completed: false });
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <form onSubmit={handleSubmit} className="bg-white p-6 rounded-xl w-full max-w-md space-y-4">
        <h2 className="text-xl font-bold">Add New Todo</h2>
        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className="w-full border p-2 rounded"
          placeholder="Todo title"
          required
        />
        <div className="flex justify-end gap-2">
          <button type="button" onClick={onClose} className="px-4 py-2 bg-slate-300 rounded">Cancel</button>
          <button type="submit" className="px-4 py-2 bg-emerald-600 text-white rounded">Add</button>
        </div>
      </form>
    </div>
  );
};

export default CreateTodoModal;

// Projects/todo-vue/src/components/CreateTodoModal.vue
<template>
  <div class="fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center">
    <div class="bg-white rounded p-6 w-full max-w-md">
      <h2 class="text-xl font-bold mb-4">➕ Create New Todo</h2>
      <form @submit.prevent="handleSubmit" class="space-y-4">
        <input v-model="title" placeholder="Enter task title" class="w-full p-2 border rounded" required />
        <label class="flex items-center gap-2">
          <input type="checkbox" v-model="completed" /> Completed
        </label>
        <div class="flex justify-end gap-4">
          <button type="button" @click="$emit('close')" class="bg-gray-300 px-4 py-2 rounded">Cancel</button>
          <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700">
            {{ saving ? 'Saving...' : 'Save' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue';
import { useTodos } from '../composables/useTodos';

export default defineComponent({
  name: 'CreateTodoModal',
  emits: ['close'],
  setup(_, { emit }) {
    const title = ref('');
    const completed = ref(false);
    const saving = ref(false);
    const { createTodo } = useTodos();

    const handleSubmit = async () => {
      saving.value = true;
      await createTodo(title.value, completed.value);
      saving.value = false;
      emit('close');
    };

    return { title, completed, saving, handleSubmit };
  },
});
</script>
